### ISSUE TITLE
slurm-cancel

### ISSUE THREAD

**Issue by Mutaz94** [A2-ai/slurmtools#3]
As a user, I want be able to cancel jobs passing model object

**Comment by mduncans** [comment]
You can now cancel a running job with `cancel_job(job_id)`

**Comment by Mutaz94** [comment]
Amazing updates! Thanks Matt

**Comment by Mutaz94** [comment]
Is it possible we get the job id from the submitted run? e.g. mod is the running model, then job_id(mod) |> cancel_job

**Comment by mduncans** [comment]
My thought process was you could `get_slurm_jobs()` and grab the job_id from there. I wanted to make cancelling a job have a little friction to prevent unwanted job cancellations. If this isn't as big of an issue as I was thinking it could definitely be added I think!
